package com.amond.kmpbook.domain.simulation.price

import kotlin.math.PI
import kotlin.math.cos
import kotlin.math.ln
import kotlin.math.sqrt

/**
 * A small, platform-independent SplitMix64 pseudo-random number generator.
 *
 * Kotlin/JVM's and Kotlin/Native's default random implementations are not part
 * of the saved-game format. This generator is: the same seed and the same call
 * order always produce the same bits on every Kotlin target.
 */
class DeterministicRandom(seed: Long) {
    private val initialSeed: Long = seed
    private var state: ULong = seed.toULong()

    /** The internal state can be persisted together with a game save. */
    fun snapshot(): Long = state.toLong()

    /** Restores a state previously returned by [snapshot]. */
    fun restore(snapshot: Long) {
        state = snapshot.toULong()
    }

    fun nextLong(): Long = nextULong().toLong()

    fun nextDouble(): Double {
        // Keep the most significant 53 random bits, matching IEEE-754's
        // exactly representable mantissa range. The result is always [0, 1).
        return (nextULong() shr 11).toDouble() * DOUBLE_UNIT
    }

    fun nextDouble(from: Double, until: Double): Double {
        require(from.isFinite() && until.isFinite()) { "Bounds must be finite" }
        require(until >= from) { "until must be greater than or equal to from" }
        return if (from == until) from else from + (until - from) * nextDouble()
    }

    fun nextInt(bound: Int): Int {
        require(bound > 0) { "bound must be positive" }
        return (nextULong() % bound.toUInt()).toInt()
    }

    fun nextBoolean(probability: Double = 0.5): Boolean {
        require(probability in 0.0..1.0) { "probability must be in [0, 1]" }
        return nextDouble() < probability
    }

    /** Standard normal variate generated with a deterministic Box-Muller step. */
    fun nextGaussian(): Double {
        val u1 = nextDouble().coerceAtLeast(MIN_POSITIVE_UNIFORM)
        val u2 = nextDouble()
        return sqrt(-2.0 * ln(u1)) * cos(2.0 * PI * u2)
    }

    fun <T> choose(values: List<T>): T {
        require(values.isNotEmpty()) { "Cannot choose from an empty list" }
        return values[nextInt(values.size)]
    }

    /**
     * Creates an independent deterministic stream without consuming this one.
     * This is useful when adding a new simulation subsystem: its random calls do
     * not perturb price history generated by existing subsystems.
     */
    fun fork(streamId: Long): DeterministicRandom =
        DeterministicRandom(mixSeed(initialSeed, streamId))

    private fun nextULong(): ULong {
        state += GOLDEN_GAMMA
        var value = state
        value = (value xor (value shr 30)) * MIX_MULTIPLIER_1
        value = (value xor (value shr 27)) * MIX_MULTIPLIER_2
        return value xor (value shr 31)
    }

    companion object {
        private const val DOUBLE_UNIT: Double = 1.0 / 9_007_199_254_740_992.0 // 2^53
        private const val MIN_POSITIVE_UNIFORM: Double = 1.0 / 9_007_199_254_740_992.0
        private const val GOLDEN_GAMMA: ULong = 0x9E3779B97F4A7C15uL
        private const val MIX_MULTIPLIER_1: ULong = 0xBF58476D1CE4E5B9uL
        private const val MIX_MULTIPLIER_2: ULong = 0x94D049BB133111EBuL

        /** Stable seed composition for stock, turn, and subsystem identifiers. */
        fun mixSeed(seed: Long, vararg keys: Long): Long {
            var mixed = seed.toULong()
            for (key in keys) {
                var value = key.toULong() + GOLDEN_GAMMA
                value = (value xor (value shr 30)) * MIX_MULTIPLIER_1
                value = (value xor (value shr 27)) * MIX_MULTIPLIER_2
                value = value xor (value shr 31)
                mixed = mixed xor value
                mixed = mixed * GOLDEN_GAMMA + MIX_MULTIPLIER_1
            }
            return mixed.toLong()
        }

        /** Stable FNV-1a key for occurrence ids and other persisted textual identities. */
        fun stableHash64(value: String): Long {
            var hash = 0xCBF29CE484222325uL
            for (character in value) {
                hash = hash xor character.code.toULong()
                hash *= 0x100000001B3uL
            }
            return hash.toLong()
        }

        /** Creates a stream whose output depends on the key, never on iteration or query order. */
        fun keyed(seed: Long, key: String): DeterministicRandom =
            DeterministicRandom(mixSeed(seed, stableHash64(key)))
    }
}
