package com.amond.kmpbook.modding.api

import com.amond.kmpbook.presentation.simulator.SimulatorUiState

internal fun SimulatorUiState.toModGameSnapshot(): ModGameSnapshot = ModGameSnapshot(
    apiVersion = MOD_API_VERSION,
    scenarioName = options.scenarioName,
    difficultyName = options.difficultyName,
    seed = options.seed,
    usFractionalTrading = options.usFractionalTrading,
    autoExchange = options.autoExchange,
    ironmanMode = options.ironmanMode,
    activeMods = options.activeMods.map { activeMod ->
        ModActiveModSnapshot(
            id = activeMod.id,
            version = activeMod.version,
            settings = activeMod.settings.toMap(),
        )
    }.toList(),
    phase = phase,
    screen = screen,
    currentTime = currentTime,
    turn = turn,
    campaignProgress = progress,
    isAtEnd = isAtEnd,
    selectedTurnStep = selectedTurnStep,
    selectedInstrumentId = selectedStockId,
    isAdvancing = isAdvancing,
    instruments = stocks.map { stock ->
        val quote = quotes.getValue(stock.id)
        ModInstrumentSnapshot(
            id = stock.id,
            symbol = stock.symbol,
            name = stock.name,
            englishName = stock.englishName,
            description = stock.description,
            market = stock.market,
            currency = stock.currency,
            sector = stock.sector,
            instrumentType = stock.instrumentType,
            quantityStep = stock.quantityStep,
            quoteTimestamp = quote.timestamp,
            price = quote.price,
            previousClose = quote.previousClose,
            changeRate = quote.changeRate,
            open = quote.open,
            high = quote.high,
            low = quote.low,
            volume = quote.volume,
            bidPrice = quote.bidPrice,
            askPrice = quote.askPrice,
            bidQuantity = quote.bidQuantity,
            askQuantity = quote.askQuantity,
            session = quote.session,
        )
    }.toList(),
    marketIndices = marketIndices.values.map { index ->
        ModMarketIndexSnapshot(
            id = index.id,
            timestamp = index.timestamp,
            value = index.value,
            previousClose = index.previousClose,
            changeRate = index.changeRate,
            open = index.open,
            high = index.high,
            low = index.low,
            constituentCount = index.constituentCount,
            sessionDate = index.sessionDate,
        )
    }.toList(),
    cashByCurrency = cashByCurrency.toMap(),
    holdings = holdings.values.map { holding ->
        ModHoldingSnapshot(
            instrumentId = holding.stockId,
            quantity = holding.quantity,
            averagePrice = holding.averagePrice,
            currentPrice = holding.currentPrice,
            currency = holding.currency,
            costBasis = holding.costBasis,
            marketValue = holding.marketValue,
            unrealizedProfit = holding.unrealizedProfit,
            realizedProfit = holding.realizedProfit,
            returnRate = holding.returnRate,
        )
    }.toList(),
    orders = orders.map { order ->
        ModOrderSnapshot(
            id = order.id,
            instrumentId = order.stockId,
            side = order.side,
            type = order.type,
            quantity = order.quantity,
            limitPrice = order.limitPrice,
            status = order.status,
            filledQuantity = order.filledQuantity,
            remainingQuantity = order.remainingQuantity,
            averageFilledPrice = order.averageFilledPrice,
            timeInForce = order.timeInForce,
            createdAt = order.createdAt,
            updatedAt = order.updatedAt,
            rejectionReason = order.rejectionReason,
        )
    }.toList(),
    trades = trades.map { trade ->
        ModTradeSnapshot(
            id = trade.id,
            orderId = trade.orderId,
            instrumentId = trade.stockId,
            side = trade.side,
            quantity = trade.quantity,
            price = trade.price,
            grossAmount = trade.grossAmount,
            currency = trade.currency,
            executedAt = trade.executedAt,
            commission = trade.commission,
            tax = trade.tax,
            settlementKind = trade.settlementKind,
            settlementDateOverride = trade.settlementDateOverride,
        )
    }.toList(),
    news = newsEvents.map { event ->
        ModNewsSnapshot(
            id = event.id,
            title = event.title,
            description = event.description,
            sourceLabel = event.sourceLabel,
            scope = event.scope,
            type = event.type,
            severity = event.severity,
            startsAt = event.startsAt,
            endsAt = event.endsAt,
            affectedMarkets = event.affectedMarkets.toSet(),
            affectedSectors = event.affectedSectors.toSet(),
            affectedInstrumentIds = event.affectedStockIds.toSet(),
            isActive = activeEvents.any { active -> active.id == event.id },
            isRead = event.id in readEventIds,
        )
    }.toList(),
    activeEventIds = activeEvents.mapTo(linkedSetOf()) { it.id }.toSet(),
    readEventIds = readEventIds.toSet(),
    readInstrumentNewsEventIds = readStockNewsEventIds.mapValues { (_, eventIds) ->
        eventIds.toSet()
    }.toMap(),
    watchlistedInstrumentIds = watchlistedStockIds.toSet(),
    macro = ModMacroSnapshot(
        policyRate = macro.policyRate,
        policyRateChange = macro.policyRateChange,
        inflationRate = macro.inflationRate,
        inflationSurprise = macro.inflationSurprise,
        growthRate = macro.growthRate,
        growthSurprise = macro.growthSurprise,
        usdKrw = macro.usdKrw,
        fxRatesToKrw = macro.fxRatesToKrw.orEmpty().toMap(),
        riskSentiment = macro.riskSentiment,
        volatilityRegime = macro.volatilityRegime,
        retailOrderFlow = macro.retailOrderFlow,
        institutionalOrderFlow = macro.institutionalOrderFlow,
        liquidityStress = macro.liquidityStress,
        newsIntensity = macro.newsIntensity,
        marketHourlyReturns = macro.marketHourlyReturns.toMap(),
        marketChangeFromPreviousClose = macro.marketChangeFromPreviousClose.toMap(),
        usCircuitBreakerLevel = macro.usCircuitBreakerLevel,
    ),
    marketSessions = marketSessions.map { (market, session) ->
        ModMarketSessionSnapshot(
            market = market,
            session = session,
            isTradable = session.isTradable,
        )
    }.toList(),
    externalMarketForcesTarget = externalMarketForcesTarget.copy(),
    portfolio = ModPortfolioSummary(
        initialCapitalKrw = initialCapitalKrw,
        cashValueKrw = cashValueKrw,
        instrumentValueKrw = stockValueKrw,
        totalAssetsKrw = totalAssetsKrw,
        unrealizedProfitKrw = unrealizedProfitKrw,
        realizedProfitKrw = realizedProfitKrw,
        totalReturnRate = totalReturnRate,
        totalCommissionKrw = totalCommissionKrw,
        totalSaleTaxKrw = totalSaleTaxKrw,
        totalTransactionCostKrw = totalTransactionCostKrw,
        totalDividendKrw = totalDividendKrw,
        peakAssetsKrw = peakAssetsKrw,
        maximumDrawdown = maximumDrawdown,
        benchmarkReturn = benchmarkReturn,
        holdingCount = holdings.size,
        openOrderCount = openOrders.size,
        tradeCount = trades.size,
    ),
    lastMessage = lastMessage,
)

internal fun SimulatorUiState.toModGameStateSummary(): ModGameStateSummary = ModGameStateSummary(
    phase = phase,
    currentTime = currentTime,
    turn = turn,
    totalAssetsKrw = totalAssetsKrw,
    selectedInstrumentId = selectedStockId,
    isAdvancing = isAdvancing,
)
