package com.amond.kmpbook.presentation

import com.amond.kmpbook.domain.data.StockCatalog
import com.amond.kmpbook.domain.model.Currency
import com.amond.kmpbook.domain.model.CorporateActionKind
import com.amond.kmpbook.domain.model.CorporateActionMath
import com.amond.kmpbook.domain.model.CorporateActionRecord
import com.amond.kmpbook.domain.model.CorporateActionSource
import com.amond.kmpbook.domain.model.toAnnouncementNewsReference
import com.amond.kmpbook.domain.model.toAppliedNewsReference
import com.amond.kmpbook.domain.model.toCancellationNewsReference
import com.amond.kmpbook.domain.model.EtfTaxCategory
import com.amond.kmpbook.domain.model.DistributionFrequency
import com.amond.kmpbook.domain.model.EtfExposureRegion
import com.amond.kmpbook.domain.model.GameEndReason
import com.amond.kmpbook.domain.model.GameEvent
import com.amond.kmpbook.domain.model.EventRecordKind
import com.amond.kmpbook.domain.model.GamePhase
import com.amond.kmpbook.domain.model.Holding
import com.amond.kmpbook.domain.model.Market
import com.amond.kmpbook.domain.model.MarketActionKind
import com.amond.kmpbook.domain.model.MarketActionReference
import com.amond.kmpbook.domain.model.MarketActionTransition
import com.amond.kmpbook.domain.model.MarketIndexId
import com.amond.kmpbook.domain.model.MarketIndexSnapshot
import com.amond.kmpbook.domain.model.MarketSession
import com.amond.kmpbook.domain.model.Order
import com.amond.kmpbook.domain.model.OrderSide
import com.amond.kmpbook.domain.model.OrderStatus
import com.amond.kmpbook.domain.model.OrderType
import com.amond.kmpbook.domain.model.PortfolioSnapshot
import com.amond.kmpbook.domain.model.PendingCorporateAction
import com.amond.kmpbook.domain.model.PriceBar
import com.amond.kmpbook.domain.model.Quote
import com.amond.kmpbook.domain.model.ReferenceCurrency
import com.amond.kmpbook.domain.model.Screen
import com.amond.kmpbook.domain.model.ScheduledEventEmission
import com.amond.kmpbook.domain.model.ScheduledEventKind
import com.amond.kmpbook.domain.model.Sector
import com.amond.kmpbook.domain.model.StockDefinition
import com.amond.kmpbook.domain.model.EventScope
import com.amond.kmpbook.domain.model.EventSeverity
import com.amond.kmpbook.domain.model.EventType
import com.amond.kmpbook.domain.model.GameEventImpact
import com.amond.kmpbook.domain.model.ImpactDirection
import com.amond.kmpbook.domain.model.InstrumentType
import com.amond.kmpbook.domain.model.InstrumentTerminationKind
import com.amond.kmpbook.domain.model.InstrumentTerminationTerms
import com.amond.kmpbook.domain.model.InstrumentTerminationValuationMethod
import com.amond.kmpbook.domain.model.resolveInstrumentTerminationAtSessionClose
import com.amond.kmpbook.domain.model.DailyListingSurveillanceInput
import com.amond.kmpbook.domain.model.ListingFinalDisposition
import com.amond.kmpbook.domain.model.ListingFinalDispositionType
import com.amond.kmpbook.domain.model.ListingLifecycleEventKind
import com.amond.kmpbook.domain.model.ListingLifecycleLedgerEvent
import com.amond.kmpbook.domain.model.ListingLifecycleReason
import com.amond.kmpbook.domain.model.ListingLifecycleState
import com.amond.kmpbook.domain.model.ListingLifecycleStatus
import com.amond.kmpbook.domain.model.ListingNoticeLevel
import com.amond.kmpbook.domain.model.ListingRecoveryCondition
import com.amond.kmpbook.domain.model.ListingRiskSeverity
import com.amond.kmpbook.domain.model.ListingRiskTag
import com.amond.kmpbook.domain.model.InvestmentAlertDesignation
import com.amond.kmpbook.domain.model.InvestmentAlertLevel
import com.amond.kmpbook.domain.model.InvestmentAlertReleaseRule
import com.amond.kmpbook.domain.model.InvestmentAlertStatus
import com.amond.kmpbook.domain.model.investmentAlertOccurrenceId
import com.amond.kmpbook.domain.model.InstrumentTradingHalt
import com.amond.kmpbook.domain.model.KrxCircuitBreakerEvent
import com.amond.kmpbook.domain.model.KrxCircuitBreakerLevel
import com.amond.kmpbook.domain.model.KrxCircuitBreakerObservation
import com.amond.kmpbook.domain.model.KrxCircuitBreakerPhase
import com.amond.kmpbook.domain.model.krxCircuitBreakerOccurrenceId
import com.amond.kmpbook.domain.model.KrxSidecarEvent
import com.amond.kmpbook.domain.model.KrxSidecarObservation
import com.amond.kmpbook.domain.model.KrxSidecarPhase
import com.amond.kmpbook.domain.model.krxSidecarOccurrenceId
import com.amond.kmpbook.domain.model.KrxViEvent
import com.amond.kmpbook.domain.model.KrxViKind
import com.amond.kmpbook.domain.model.KrxViObservation
import com.amond.kmpbook.domain.model.KrxViPhase
import com.amond.kmpbook.domain.model.KrxViProductClass
import com.amond.kmpbook.domain.model.KrxViSession
import com.amond.kmpbook.domain.model.krxViOccurrenceId
import com.amond.kmpbook.domain.model.MarketMoveDirection
import com.amond.kmpbook.domain.model.TradingDayWindow
import com.amond.kmpbook.domain.model.TradingHaltReason
import com.amond.kmpbook.domain.model.TradingHaltStatus
import com.amond.kmpbook.domain.model.TradingProtectionAction
import com.amond.kmpbook.domain.model.TradingProtectionRequest
import com.amond.kmpbook.domain.model.TradingProtectionSnapshot
import com.amond.kmpbook.domain.model.UsLuldEvent
import com.amond.kmpbook.domain.model.UsLuldLimitSide
import com.amond.kmpbook.domain.model.UsLuldObservation
import com.amond.kmpbook.domain.model.UsLuldPhase
import com.amond.kmpbook.domain.model.UsLuldTier
import com.amond.kmpbook.domain.model.usLuldOccurrenceId
import com.amond.kmpbook.domain.model.UsMwcbEvent
import com.amond.kmpbook.domain.model.UsMwcbLevel
import com.amond.kmpbook.domain.model.UsMwcbObservation
import com.amond.kmpbook.domain.model.UsMwcbPhase
import com.amond.kmpbook.domain.model.UsMwcbState
import com.amond.kmpbook.domain.model.UsMwcbVenuePhase
import com.amond.kmpbook.domain.model.UsMwcbVenueStatus
import com.amond.kmpbook.domain.model.usMwcbOccurrenceId
import com.amond.kmpbook.domain.model.TimeInForce
import com.amond.kmpbook.domain.model.Trade
import com.amond.kmpbook.domain.model.TradeSettlementKind
import com.amond.kmpbook.domain.model.TurnStep
import com.amond.kmpbook.domain.simulation.DeterministicRandom
import com.amond.kmpbook.domain.simulation.EventEngine
import com.amond.kmpbook.domain.simulation.EventGenerationContext
import com.amond.kmpbook.domain.simulation.EventShockCalculator
import com.amond.kmpbook.domain.simulation.MacroEnvironment
import com.amond.kmpbook.domain.simulation.MarketMicrostructure
import com.amond.kmpbook.domain.simulation.ListingLifecycleEngine
import com.amond.kmpbook.domain.simulation.ListingRemediationDecisionStatus
import com.amond.kmpbook.domain.simulation.ListingRemediationPolicy
import com.amond.kmpbook.domain.simulation.TradingProtectionEngine
import com.amond.kmpbook.domain.simulation.TradingProtectionRules
import com.amond.kmpbook.domain.simulation.MarketIndexCalculationInput
import com.amond.kmpbook.domain.simulation.MarketIndexEngine
import com.amond.kmpbook.domain.simulation.OrderBookEngine
import com.amond.kmpbook.domain.simulation.OrderBookGenerationInput
import com.amond.kmpbook.domain.simulation.OrderBookSnapshot
import com.amond.kmpbook.domain.simulation.PriceEngine
import com.amond.kmpbook.domain.simulation.PriceGenerationInput
import com.amond.kmpbook.domain.simulation.ScheduledEventEngine
import com.amond.kmpbook.domain.tax.AnnualStockTaxCalculator
import com.amond.kmpbook.domain.tax.AnnualStockTaxRequest
import com.amond.kmpbook.domain.tax.BrokerFeeCalculator
import com.amond.kmpbook.domain.tax.BrokerFeeRequest
import com.amond.kmpbook.domain.tax.BrokerFeeSchedule
import com.amond.kmpbook.domain.tax.DividendTaxCalculator
import com.amond.kmpbook.domain.tax.DividendTaxClass
import com.amond.kmpbook.domain.tax.DividendTaxRequest
import com.amond.kmpbook.domain.tax.DomesticSaleTaxCalculator
import com.amond.kmpbook.domain.tax.DomesticSaleTaxRequest
import com.amond.kmpbook.domain.tax.DomesticEtfSaleTaxCalculator
import com.amond.kmpbook.domain.tax.DomesticEtfSaleTaxRequest
import com.amond.kmpbook.domain.tax.ForeignInstrumentTaxClass
import com.amond.kmpbook.domain.tax.FifoCostBasisBook
import com.amond.kmpbook.domain.tax.MoneyAmount
import com.amond.kmpbook.domain.tax.MoneyRoundingPolicy
import com.amond.kmpbook.domain.tax.MajorShareholderAssessmentRequest
import com.amond.kmpbook.domain.tax.MajorShareholderCalculator
import com.amond.kmpbook.domain.tax.RealizedStockGain
import com.amond.kmpbook.domain.tax.ShareholderHoldingSnapshot
import com.amond.kmpbook.domain.tax.ShareholderRelation
import com.amond.kmpbook.domain.tax.StockGainTaxTreatment
import com.amond.kmpbook.domain.tax.TaxRate
import com.amond.kmpbook.domain.time.DefaultMarketHolidays
import com.amond.kmpbook.domain.time.GameCalendar
import kotlinx.datetime.DateTimeUnit
import kotlinx.datetime.DayOfWeek
import kotlinx.datetime.LocalDate
import kotlinx.datetime.LocalTime
import kotlinx.datetime.Month
import kotlinx.datetime.minus
import kotlinx.datetime.plus
import kotlinx.datetime.toLocalDateTime
import kotlin.math.abs
import kotlin.math.exp
import kotlin.math.floor
import kotlin.math.ln
import kotlin.math.round
import kotlin.time.Duration.Companion.hours
import kotlin.time.Duration.Companion.minutes
import kotlin.time.Duration.Companion.nanoseconds
import kotlin.time.Duration.Companion.seconds
import kotlin.time.Instant

internal data class RuntimeTradingInterval(
    val startsAt: Instant,
    val endsAt: Instant,
) {
    init {
        require(endsAt > startsAt) { "거래 가능 구간의 종료 시각은 시작 시각보다 뒤여야 합니다." }
    }
}
