package com.amond.kmpbook.domain.model

import kotlinx.datetime.LocalDate

/** 일별 감시 입력에 붙는 구조화된 위험 신호. */
enum class ListingRiskTag {
    LISTING_MAINTENANCE_DEFICIENCY,
    ADMINISTRATIVE_ISSUE,
    LOW_BID_PRICE,
    LOW_MARKET_CAPITALIZATION,
    LOW_TRADING_LIQUIDITY,
    AUDIT_OPINION_FAILURE,
    DISCLOSURE_VIOLATION,
    SERIOUS_COMPLIANCE_EVENT,
    BANKRUPTCY_OR_INSOLVENCY,
    CORE_BUSINESS_SUSPENSION,
    QUALITATIVE_LISTING_REVIEW,
    ETF_LIQUIDATION_APPROVED,
    ETN_MATURITY_OR_EARLY_REDEMPTION,
    ISSUER_ELIGIBILITY_FAILURE,
    UNDERLYING_INDEX_UNAVAILABLE,
    LIQUIDITY_PROVIDER_FAILURE,
}
